MAVEN_ARTIFACTS = [
    "io.kubernetes:client-java-api:14.0.1",
    "io.vavr:vavr:0.10.3",
    "org.apache.commons:commons-compress:1.21",
    "org.yaml:snakeyaml:1.30",
    "com.fasterxml.jackson.core:jackson-databind:2.13.3",
    "com.fasterxml.jackson.core:jackson-core:2.13.3",
    "com.fasterxml.jackson.core:jackson-annotations:2.13.3",
    "io.swagger.codegen.v3:swagger-codegen:3.0.35",
    "io.swagger.codegen.v3:swagger-codegen-generators:1.0.34",
    "io.swagger.parser.v3:swagger-parser-v3:2.1.1",
    "io.swagger.core.v3:swagger-models:2.2.1",
    "com.github.jknack:handlebars:4.3.0",
    "javax.validation:validation-api:2.0.1.Final",
    "io.kubernetes:client-java-api:16.0.0",
    "info.picocli:picocli:4.6.3",
]
